servers:
  - server: "localhost:11211"
    displayName: localhost
  - server: "myUbuntu.sandbox.appdynamics.com:11211"
    displayName: myUbuntu

metricPathPrefix:  "Custom Metrics|Memcached|"


# Metric Overrides. Change/Uncomment this if you want to transform the metric key or want more control on the metrics.
# Not so common to change it.
#----------------------------------------------------------------------------------------------------------------------
#metricOverrides:
#  - metricKey: ".*Ratio.*"
#    postfix: "Percent"
#    multiplier: 100

#  - metricKey: ".*Cache.*Rate.*"
#    postfix: "Percent"
#    multiplier: 100

